const fs = require("fs");

const data = {
  SmartContractVulnerabilityCover: [
    { ProductID: 1, Protocol: "Alpha Homora V1" },
    { ProductID: 2, Protocol: "Yearn Finance (all vaults)" },
    { ProductID: 3, Protocol: "MakerDAO MCD" },
    { ProductID: 4, Protocol: "Curve (All Protocols)" },
    { ProductID: 5, Protocol: "Uniswap V2" },
    { ProductID: 5, Protocol: "SushiSwap V1" },
    { ProductID: 5, Protocol: "Eth 2.0" },
    { ProductID: 5, Protocol: "Aave V2" },
    { ProductID: 5, Protocol: "Compound V2" },
    { ProductID: 5, Protocol: "Synthetix" },
    { ProductID: 5, Protocol: "Balancer V1" },
    { ProductID: 5, Protocol: "Vesper" },
    { ProductID: 5, Protocol: "RenVM" },
    { ProductID: 5, Protocol: "DyDx" },
    { ProductID: 5, Protocol: "Bancor V2" },
    { ProductID: 5, Protocol: "Reflexer V2" },
    { ProductID: 5, Protocol: "1inch" },
    { ProductID: 5, Protocol: "mStable" },
    { ProductID: 5, Protocol: "Badger Finance" },
    { ProductID: 5, Protocol: "HEGIC" },
    { ProductID: 5, Protocol: "88mph V2" },
    { ProductID: 5, Protocol: "Maple" },
    { ProductID: 5, Protocol: "Venus" },
    { ProductID: 5, Protocol: "Pancakeswap" },
    { ProductID: 5, Protocol: "DODO V2" },
    { ProductID: 5, Protocol: "Autofarm" },
    { ProductID: 5, Protocol: "Raydium" },
    { ProductID: 5, Protocol: "QuickSwap" },
    { ProductID: 5, Protocol: "Spirit Swap" },
    { ProductID: 5, Protocol: "SpookySwap" },
    { ProductID: 5, Protocol: "Homora V2" },
    { ProductID: 5, Protocol: "Uniswap V3" },
    { ProductID: 5, Protocol: "Bella" },
    { ProductID: 5, Protocol: "Convex" },
    { ProductID: 5, Protocol: "Balancer V2" },
    { ProductID: 5, Protocol: "Lido" },
    { ProductID: 5, Protocol: "Alchemix V2" },
    { ProductID: 5, Protocol: "KyberSwap" },
    { ProductID: 5, Protocol: "Harvest Finance" },
    { ProductID: 5, Protocol: "Perpetual Protocol" },
    { ProductID: 5, Protocol: "dHEDGE" },
    { ProductID: 5, Protocol: "Pendle" },
    { ProductID: 5, Protocol: "Impossible Finance" },
    { ProductID: 5, Protocol: "TrueFi" },
    { ProductID: 5, Protocol: "Alpaca Finance" },
    { ProductID: 5, Protocol: "Element Finance" },
    { ProductID: 5, Protocol: "Mai Protocol V3" },
    { ProductID: 5, Protocol: "Tranchess" },
    { ProductID: 5, Protocol: "Liquity" },
    { ProductID: 5, Protocol: "Benqi" },
    { ProductID: 5, Protocol: "Pangolin" },
    { ProductID: 5, Protocol: "Trader JOE" },
    { ProductID: 5, Protocol: "Yield YAK" },
    { ProductID: 5, Protocol: "88mph V3" },
    { ProductID: 5, Protocol: "Gnosis Safe" },
    { ProductID: 5, Protocol: "Olympus DAO" },
    { ProductID: 5, Protocol: "Abracadabra.money" },
    { ProductID: 5, Protocol: "ApeSwap" },
    { ProductID: 5, Protocol: "Beefy" },
    { ProductID: 5, Protocol: "Origin Dollar" },
    { ProductID: 5, Protocol: "Loopring" },
    { ProductID: 5, Protocol: "NAOs Finance Fornation V2" },
    { ProductID: 5, Protocol: "Port Finance" },
    { ProductID: 5, Protocol: "Enzyme Finance" },
    { ProductID: 5, Protocol: "Frax Finance" },
    { ProductID: 5, Protocol: "Tokemak" },
    { ProductID: 5, Protocol: "Pool Together V4" },
    { ProductID: 5, Protocol: "Saddle Finance" },
    { ProductID: 5, Protocol: "GMX" },
    { ProductID: 5, Protocol: "Balanced Network" },
    { ProductID: 5, Protocol: "Hector DAO" },
    { ProductID: 5, Protocol: "Aldrin DEX" },
    { ProductID: 5, Protocol: "Tinlake" },
    { ProductID: 5, Protocol: "Idle V4" },
    { ProductID: 5, Protocol: "ICHI" },
    { ProductID: 5, Protocol: "Tulip Porotocol" },
    { ProductID: 5, Protocol: "VVS Finance" },
    { ProductID: 5, Protocol: "QiDao" },
    { ProductID: 5, Protocol: "Tetu" },
    { ProductID: 5, Protocol: "Angle Protocol" },
    { ProductID: 5, Protocol: "Wing Finance" },
    { ProductID: 5, Protocol: "Scream" },
    { ProductID: 5, Protocol: "Ribbon Finance" },
    { ProductID: 5, Protocol: "Gains Network (DAI Vault)" },
    { ProductID: 5, Protocol: "KeeperDAO" },
    { ProductID: 5, Protocol: "Apricot Finance" },
    { ProductID: 5, Protocol: "Saber" },
    { ProductID: 5, Protocol: "Francium" },
    { ProductID: 5, Protocol: "Liquid Driver" },
    { ProductID: 5, Protocol: "Reaper Farm" },
    { ProductID: 5, Protocol: "Platypus Finance" },
    { ProductID: 5, Protocol: "Biswap" },
    { ProductID: 5, Protocol: "Beethoven X" },
    { ProductID: 5, Protocol: "Marinade Finance" },
    { ProductID: 5, Protocol: "StakeDAO" },
    { ProductID: 5, Protocol: "Zenlink" },
    { ProductID: 5, Protocol: "Elephant Money" },
    { ProductID: 5, Protocol: "Geist Finance" },
    { ProductID: 5, Protocol: "Defrost Finance" },
    { ProductID: 5, Protocol: "Ellipsis Finance" },
    { ProductID: 5, Protocol: "Mantra DAO" },
    { ProductID: 5, Protocol: "AAVE V3" },
    { ProductID: 5, Protocol: "Notional Finance" },
    { ProductID: 5, Protocol: "Goldfinch" },
    { ProductID: 5, Protocol: "Deri Protocol" },
    { ProductID: 5, Protocol: "Planet" },
    { ProductID: 5, Protocol: "BabySwap" },
    { ProductID: 5, Protocol: "SingleFinance" },
    { ProductID: 5, Protocol: "IDEX V3" },
    { ProductID: 5, Protocol: "Impermax Finance" },
    { ProductID: 5, Protocol: "Ten Finance (excl. Lend)" },
    { ProductID: 5, Protocol: "Solend" },
    { ProductID: 5, Protocol: "Bancor V3" },
    { ProductID: 5, Protocol: "KnightSwap" },
    { ProductID: 5, Protocol: "iziSwap" },
    { ProductID: 5, Protocol: "WombatExchange" },
    { ProductID: 5, Protocol: "Yeti Finance" },
    { ProductID: 5, Protocol: "StellaSwap" },
    { ProductID: 5, Protocol: "Hubble" },
    { ProductID: 5, Protocol: "Ola Finance" },
    { ProductID: 5, Protocol: "Compound V3" },
    { ProductID: 5, Protocol: "Aura Finance" },
    { ProductID: 5, Protocol: "Stader" },
    { ProductID: 5, Protocol: "SingularityDAO (excl. dynDYDX and Launchpad)" },
    { ProductID: 5, Protocol: "Defrost Finance V2" },
    { ProductID: 5, Protocol: "Gearbox" },
    { ProductID: 5, Protocol: "Moonwell Artemis" },
    { ProductID: 5, Protocol: "Magpie" },
    { ProductID: 5, Protocol: "Euler" },
    { ProductID: 5, Protocol: "Instadap" },
    { ProductID: 5, Protocol: "Helio Protocol" },
    { ProductID: 5, Protocol: "Amulet Protocol" },
    { ProductID: 5, Protocol: "Sturdy" },
    { ProductID: 5, Protocol: "Ensuro V2" },
    { ProductID: 5, Protocol: "Velodrome Finance" },
    { ProductID: 5, Protocol: "Exactly Protocol" },
    { ProductID: 5, Protocol: "Carbon" },
    { ProductID: 5, Protocol: "Alpaca Finance V2" },
    { ProductID: 5, Protocol: "Nested" },
    { ProductID: 5, Protocol: "Origin Ether" },
    { ProductID: 5, Protocol: "Level Finance" },
    { ProductID: 5, Protocol: "Figment" },
    { ProductID: 5, Protocol: "dForce" },
    { ProductID: 5, Protocol: "Lyra" },
    { ProductID: 5, Protocol: "Orca" },
    { ProductID: 5, Protocol: "Babydog eSwap" },
    { ProductID: 5, Protocol: "GMX V2" },
    { ProductID: 5, Protocol: "Amulet Audit Refund Cover" },
    { ProductID: 5, Protocol: "Extra Finance" },
    { ProductID: 5, Protocol: "CIAN" },
  ],
  CustodianRiskCover: [
    // Custodian risk cover products
    { ProductID: 32, Protocol: "Binance" },
    { ProductID: 33, Protocol: "Coinbase" },
  ],
  StablecoinDePegRiskCover: [
    // Stablecoin de-peg risk cover products
    { ProductID: 99, Protocol: "USDT" },
    { ProductID: 103, Protocol: "MIM" },
    { ProductID: 173, Protocol: "BUSD" },
    { ProductID: 187, Protocol: "USDC" },
  ],
};

// Convert the JavaScript object to a JSON string
const jsonData = JSON.stringify(data, null, 2);

// Write the JSON data to a file
fs.writeFile("products.json", jsonData, "utf8", (err) => {
  if (err) {
    console.error("An error occurred while writing JSON Object to File.", err);
  } else {
    console.log("JSON file has been saved.");
  }
});
